import React, { useEffect, useState } from "react";
import { downloadRoadmap } from "./formHelpers";

type Step4Props = {
  prevStep: () => void;
  formData: {
    initialPrompt: string;
    productType: string;
    projectGoal: string;
    projectCategory: string;
    teamName: string;
    members: Array<{
      id: number;
      name: string;
      skills: string;
      role: string;
    }>;
  };
};

const Step4: React.FC<Step4Props> = ({ prevStep, formData }) => {
  const [loading, setLoading] = useState(true);
  const [roadmapGenerated, setRoadmapGenerated] = useState(false);

  useEffect(() => {
    // Simulate AI processing with a delay
    const timer = setTimeout(() => {
      setLoading(false);
      setRoadmapGenerated(true);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="step-content active" id="step4">
      {loading && (
        <div id="loadingState">
          <div className="loading-container">
            <div className="loading-spinner"></div>
            <h3 className="loading-text">
              <span className="ai-name">Ideagenie</span> is crafting your roadmap
            </h3>
            <p className="loading-subtext">
              Analyzing your project requirements and team composition...
            </p>
            <div className="pulse">
              <i className="fas fa-brain" style={{ fontSize: "2rem", color: "var(--primary)" }}></i>
            </div>
          </div>
        </div>
      )}      {!loading && roadmapGenerated && (
        <div id="roadmapOutput" className="roadmap-output">
          <div className="roadmap-container">
            <div className="roadmap-header">
              <h1 className="roadmap-title">
                <i className="fas fa-map-marked-alt"></i> Project Roadmap
              </h1>
              <div className="roadmap-badge">AI-Generated by Ideagenie</div>
            </div>

            <div className="roadmap-section">
              <h2 className="roadmap-section-title">
                <i className="fas fa-project-diagram"></i> Workflow Division
              </h2>
              <ul className="roadmap-list">
                <li>
                  <strong>Phase 1: Discovery & Research</strong> (2 weeks) - Market
                  analysis, user research, and competitive benchmarking
                </li>
                <li>
                  <strong>Phase 2: Prototype Development</strong> (3 weeks) - Build MVP
                  with core functionality for user testing
                </li>
                <li>
                  <strong>Phase 3: Iteration & Refinement</strong> (2 weeks) -
                  Incorporate feedback and improve product
                </li>
                <li>
                  <strong>Phase 4: Launch Preparation</strong> (1 week) - Final
                  testing, documentation, and marketing materials
                </li>
              </ul>
            </div>

            <div className="roadmap-divider"></div>

            <div className="roadmap-section">
              <h3 className="problem-title">
                <i className="fas fa-exclamation-triangle"></i> Problem 1: Resource
                Allocation
              </h3>
              <ul className="roadmap-list">
                <li>
                  <strong>Financial Feasibility:</strong> Estimated budget of $28,500
                  required for development and launch
                </li>
                <li>
                  <strong>Source:</strong> Recommend bootstrapping initial phase ($15k)
                  followed by seed funding
                </li>
                <li>
                  <strong>Trading:</strong> Potential partnerships with complementary
                  service providers for resource sharing
                </li>
              </ul>
            </div>

            <div className="roadmap-divider"></div>

            <div className="roadmap-section">
              <h3 className="problem-title">
                <i className="fas fa-exclamation-triangle"></i> Problem 2: Technical
                Implementation
              </h3>
              <ul className="roadmap-list">
                <li>
                  <strong>Overview:</strong> Requires full-stack development with
                  scalable architecture
                </li>
                <li>
                  <strong>Tech Stack:</strong> React.js (Frontend), Node.js (Backend),
                  MongoDB (Database), AWS (Hosting)
                </li>
                <li>
                  <strong>More Research:</strong> Needed on authentication solutions and
                  data security compliance
                </li>
              </ul>
            </div>

            <div className="roadmap-note">
              <i className="fas fa-lightbulb"></i>{" "}
              <strong>Pro Tip:</strong> Get data from problem source and conduct
              additional research before finalizing implementation.
            </div>            <div className="roadmap-actions roadmap-actions-responsive">
              <button className="btn btn-outline" onClick={prevStep}>
                <i className="fas fa-edit"></i> Edit Details
              </button>
              <button className="btn btn-primary" onClick={downloadRoadmap}>
                <i className="fas fa-download"></i> Download Roadmap
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Step4;