"use client";

import React from 'react';
import { PipelineProvider } from '../../../components/PipelineContext';
import MindMapScene from '../../../components/mindmap/MindMapScene';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';

export default function UserMindMap() {
  const params = useParams();
  const router = useRouter();
  const userId = params.userId as string;

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 text-white">
      <div className="container mx-auto px-4 py-8">
        <header className="mb-8 flex flex-col md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-3xl font-bold mb-2">Your Idea Mindmap</h1>
            <p className="text-gray-300">
              Explore your idea visualization and insights generated by IdeaGenie
            </p>
          </div>
          <div className="mt-4 md:mt-0 flex gap-4">
            <Link href="/form" className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-md text-white text-sm transition-colors">
              Create New Project
            </Link>
            <button 
              onClick={() => {
                const url = window.location.href;
                navigator.clipboard.writeText(url);
                alert('URL copied to clipboard!');
              }}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-md text-white text-sm transition-colors"
            >
              Share Mindmap
            </button>
          </div>
        </header>

        <div className="bg-gray-800 rounded-xl shadow-xl p-4 h-[80vh]">
          <PipelineProvider userId={userId}>
            <MindMapScene usePipelineData={true} />
          </PipelineProvider>
        </div>
        
        <div className="mt-6 text-center text-sm text-gray-400">
          <p>This is your personal mindmap URL: <span className="font-mono">{`/${userId}/mindmap`}</span></p>
          <p className="mt-2">Bookmark this page to access your mindmap later</p>
        </div>
      </div>
    </div>
  );
}
